### ISSUE TITLE
Feature request: "clear board"

### ISSUE THREAD

**Issue by chlab** [patricsteiner/retronyx#36]
Hey Onyxers

It would be useful to have a button to clear all entries from the board before/after a meeting if there are still things leftover from last time. What do you think?

**Comment by patricsteiner** [comment]
Hi Christof, thanks for the request :)
Currently, this is only possible if you are the creator of the board... (creator = the temporary & anonymous user that was automatically created in the background). 

![grafik](https://user-images.githubusercontent.com/7628757/172836332-7059b4c5-4842-441e-aa56-4dd55b10a4c6.png)

We decided to not have permanent accounts on onyxretro for several reasons:
1. Usability: we want everyone to be able to use the product without having to login
2. Simplicity: Keep the product as simple as possible (from a feature perspective)
3. To be honest, I'm lazy and very busy at the moment. But you are very welcome to open a PR ;)

Cheers 😁✌

**Comment by chlab** [comment]
Ah ok that's the problem then. Our board owner is on a sabbatical :)

**Comment by patricsteiner** [comment]
@chlab Sorry 😅 you can always just create a new board :P
